### ISSUE TITLE
Check in New Implementation

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#114]
Hey @yymao  - you said you would check in your new likelihood function implementation code, would you mind, please? If you do it as a pull request, we will be able to see what you have added, and comment on any lines we don't understand. Thanks!

**Comment by yymao** [comment]
resolved by 10be2a6

**Comment by drphilmarshall** [comment]
Excellent, thanks Yao! :-)
