### ISSUE TITLE
Moving beyond Gonzalez, Kravtsov & Gnedin (2014)

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#34]
The context of this project is set by [this paper](http://adsabs.harvard.edu/abs/2011ApJ...743...40B) by Gonzalez, Kravtsov & Gnedin, who applied the halo sampling technique to LG analogs from Bolshoi while we were setting up to work on Consuelo using the new observational (M31 and M33 proper motion) constraints. @marxwillia you should read their paper carefully, and write up your notes in the introduction of our paper (including how we are extending GKG's work).

**Comment by marxwillia** [comment]
Quick Question @drphilmarshall : The link in the above description doesn't go to a paper by Rodriguez, Kravtsov, and Gnedin.  It did however link to a very relevant paper by you, Risa, and Michael.  I read the paper that it linked to and wrote notes, but is there another paper that you want me to read by the three authors you mentioned?

**Comment by drphilmarshall** [comment]
Dang, sorry - I thought I'd updated the link. Can you please locate the
correct paper by those three authors, fix the link in the README and then
digest the paper? Thanks!

**Comment by marxwillia** [comment]
Current plan from @drphilmarshall and @marxwillia:  

Part 1: Check the results from Gonzalez et al.
    - Mass of Local Group (MW + M31) from Consuelo pairs.
    - Timing argument mass bias, from Consuelo pairs.
Part 2: Extend Gonzalez et al by adding M33
    - New constraints on mass of Local Group
    - New Timing Argument bias check.
Part 3: Investigate other halo properties
    - Angular momentum
    - Halo shapes

**Comment by drphilmarshall** [comment]
I think the "moving beyond Gonzales" plan is ingrained at this point, closing this issue.
