### ISSUE TITLE
Overlay model likelihood on prior triplet contours

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#43]
Plot in physical units, and smooth the contours.

**Comment by marxwillia** [comment]
NB. This will help quantify how surprising our actual Local Group is relative to our prior. See also #44  I guess

**Comment by drphilmarshall** [comment]
This is a very useful diagnostic plot - let's make it!

**Comment by drphilmarshall** [comment]
Depends on #53 !

**Comment by marxwillia** [comment]
Overlay plots of observations with model and consuelo prior with model are now located in the thesis/plots folder.

**Comment by drphilmarshall** [comment]
Beautiful!
