### ISSUE TITLE
Plot prior and posterior halo distributions

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#45]
Choose logical color schemes.  This is another Triplet method.

**Comment by marxwillia** [comment]
I will only work on this if I provide a "unblind" option for these plots.  Plotting must be blind by default!  We can only unblind at the very end when we are confident that the entire pipeline has been implemented correctly.

**Comment by marxwillia** [comment]
This depends on #50

**Comment by drphilmarshall** [comment]
Posterior plots are now being made as a matter of course, closing this one.
