### ISSUE TITLE
2D PDF contours need to be just smooth enough

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#48]
Triangle *should* get this right automagically. If it doesn't, we can look up optimal histogram bin sizes and smoothing widths in Ivezic et al, and either set them by hand, or modify the triangle defaults. The latter option is more community-spirited...but we can start with the former! :-)

**Comment by drphilmarshall** [comment]
I can help with this once #51 is resolved - then I can play around with triangle's smoothing, contouring and presentation.

**Comment by marxwillia** [comment]
Currently uses the smoothing in pappy's pdf2d.

**Comment by drphilmarshall** [comment]
Good!

triangle.py just got a bunch of updates (I was with Formean-Mackey at a
workshop last week) - git pull and check out the "philsplot" test figure
and code.
