### ISSUE TITLE
Blind plots

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#50]
Create a random seed field that is stored in the Triplet class.  It is okay for us to know the seed, but we will have a rapidly oscillating function that turns the seed into an offset.  The offset will never be stored.  All plots of non-observable halo properties (halo masses, momentum, shape, etc) must be blinded using this offset.

**Comment by drphilmarshall** [comment]
I think we have jumped over this step, to plotting unblinded masses. The detailed comparison with Van Der Marel wasn't finished before we plotted the masses, but we can go back to debugging the velocities (#52) and then re-plot. We just won't be able to make a clean statement about blind mass estimation in the write-up.
