### ISSUE TITLE
Small sample dataset for testing purposes

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#51]
Let's check in a few thousand Consuelo triplets that will allow anyone to do quick test analyses and plots just by checking out the repo. This is also an additional form of blinding (because there will be some Poisson error on the small number of good triplets...)

**Comment by drphilmarshall** [comment]
Also, once this is checked in and the demo and notes books are working from it, I can help improve the triangle plots...

**Comment by drphilmarshall** [comment]
... which is to say that issue #48 depends on this one.

**Comment by drphilmarshall** [comment]
OK @marxwillia, the demo now works for me, using your pickled data. Thanks! Try running the code yourself to make sure you can also make latex plot labels... I'll move onto tweaking `triangle` next - but first will need to issue some dependence stuff...
