### ISSUE TITLE
Enable following of thesis-writing?

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#54]
We can use overleaf read-only links to advertise the paper/thesis as you write it, from the README. Here's [Marc's thesis](https://www.overleaf.com/read/pxsmhcmkwdmh), for example. If you want people to follow along as you write, you could add this link to the README. If we were developing the latex in this repo, we would just point out the link to the checked-in PDF file.

**Comment by marxwillia** [comment]
We will be doing all the latex writing for the thesis and paper at Overleaf.  See the main README.md for links.  There will be a periodically updated copy of the tex files kept in the doc folder.  This copy is NOT to be edited and is instead for backing up the work on Overleaf.
