### ISSUE TITLE
Dependence on Yao's scripts

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#55]
The header of `triplet.py` now contains the following comment:

    # PJM: the script below is not generally available.
    # We either need a standalone version that is part of this package,
    # or we import a web-available package and provide dependency
    # instructions in the README.
    # sys.path.append('/afs/slac.stanford.edu/u/ki/yymao/scripts')
    # from readHlist import readHlist

I found @yymao's code on [bitbucket](https://bitbucket.org/yymao/) but this particular script is not checked in. The right thing to do here is for us to add a section to the README explaining how to install Yao's scripts, and then adjust the code in `triplet.py` code to import them properly, with a `try` statement. But first, we need you to check in `SimulationAnalysis.py`, Yao! I'd suggest packaging all your simulation access scripts together in a suitably-named bitbucket repo, so that we can just `import yao` :-) What do you think?

**Comment by yymao** [comment]
Simulation Analysis is in my bitbucket repo:

https://bitbucket.org/yymao/scripts/src/master/SimulationAnalysis.py

**Comment by drphilmarshall** [comment]
Are you sure that's a public repo? "scripts" doesn't show on your home page
on bitbucket...

**Comment by yymao** [comment]
Ah, this "script repo" is not public and I don't think I'll make it public in the near future. 

I just put the "SimulationAnalysis.py" file into a Gist so you can point to it there:
https://gist.github.com/yymao/91b3abd7e292e9422afa

**Comment by yymao** [comment]
Done. I have made the repo public:

https://bitbucket.org/yymao/helpers/src/master/SimulationAnalysis.py

**Comment by marxwillia** [comment]
Thanks Yao.  I will update the code so that we just import helpers.
