### ISSUE TITLE
Extract numerical values for mass measurements, compare with Gonzales

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#57]
Aim to have thesis/main.pdf ready to show at group meeting on April 6th. 

* [ ] Mass of local group from pairs analysis, cf Gonzales. Consuelo vs Bolshoi?
* [x] Mass of local group from triplets, but not using M33 kinematics
* [x] Mass of local group form triplets, including M33 kinematics. 
* [x] Plot showing three 1-D PDFs, overlaid.

* [x] Mass of Milky Way, same set of constraints. 

* [ ] Timing argument masses, in pairs analysis, compared with actual local group mass (sum of MW and M31 masses). 

DIscussion of numerical values and uncertainties - these need extracting accurately from `triangle.`

**Comment by marxwillia** [comment]
See #59 about h-dependence.

**Comment by yymao** [comment]
Not exactly related to this issue --- how much do M33 kinematics help narrowing, if any, the halo mass of M31?

**Comment by marxwillia** [comment]
Extracting numbers, comparison with Gonzalez is being done constantly now.
