### ISSUE TITLE
Make masses, etc all h-free

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#59]
By using the same value of h as Gonzales et al.

**Comment by yymao** [comment]
should the value of h be that of the simulations? i.e. simply h=0.7?

**Comment by drphilmarshall** [comment]
Yes, I think so.

**Comment by marxwillia** [comment]
Triplet.read_sim() now takes h as a parameter. The default is h=0.7

**Comment by drphilmarshall** [comment]
Great! Is the demo and thesis latex up to date with new mass posteriors?

**Comment by marxwillia** [comment]
I just issued myself to update the demo.  I am organizing all the new plots that I am making, and the thesis latex will be updated by tomorrow.  I will be meeting with @rhw in the afternoon.

**Comment by drphilmarshall** [comment]
Great! I'll follow the "update" issues and comment. You are closing in,
Marc! :-)

**Comment by marxwillia** [comment]
In terms of organizing my notebooks, I've found it easiest to actually have a separate notebook for each of the different isolation criteria:  MW-M31 pairs only, Triplets (only M33 existence), Triplets (M33 dynamics), Triplets (Consuelo prior fit by GMM).  The notes.ipynb was just getting confusing and cluttered otherwise.

**Comment by drphilmarshall** [comment]
Sounds good. You should make nbviews of each one and add the links to the
README, so we can follow along better.

**Comment by drphilmarshall** [comment]
Are all h problems, including physical/comoving distance confusion, now resolved? If all calculations are being done self-consistently and the mass results are now correct, we can re-close this issue.

**Comment by marxwillia** [comment]
There is functionality in the code for dealing with both h and a values.  We found that Michael's data files had been transformed to physical units.  I am unsure whether his masses are in units of Msun or Msun/h, and i'm not sure if there is any way to check this since the halo ID's don't seem to match from his files to the hlist.  In any case, the new isolation criteria will be used on the consuelo hlists, so this is not really an issue.

**Comment by drphilmarshall** [comment]
"I am unsure whether his masses are in units of Msun or Msun/h"

This sounds like a problem for the posterior PDF plots and credible
intervals in your thesis, unless you are already using the consuelo hlists
in that work (and so are sure you know what the units are). Can you please
just confirm that the numbers and axis labels in your thesis are correct?
