### ISSUE TITLE
Use new triangle.py functionality in plots

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#60]

**Comment by marxwillia** [comment]
Actually having some issues with the filling of contours in the new triangle functionality.  I am currently still using a hacked version of the old triangle, but I made more changes inspired by the new triangle functionality.  Eventually the new triangle package needs to be used, but I've spent so much time trying to make the plots work correctly that for the purposes of finishing the thesis, I am ignoring this issue until the paper writing.

**Comment by drphilmarshall** [comment]
New plots look good, closing this
