### ISSUE TITLE
Optimal histogram bin size

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#62]
Look up in Ivezic textbook, adapt triangle.py...

**Comment by marxwillia** [comment]
Can either use cross validation, or a rule like Scott's rule or Freedman-Diaconis rule.

**Comment by drphilmarshall** [comment]
If you are happy with how the histograms currently appear, and are
confident that the choice of binning is not affecting our numerical
results, you can close this issue.

**Comment by drphilmarshall** [comment]
Triangle plots look good enough, I think - closing this
