### ISSUE TITLE
Explore additional Consuelo epochs

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#63]
Check Busha et al 2011, Kravtsov for advice on doing this... Isolation criteria have to be consistent.
Correct for different scale factor / h at higher z?

**Comment by marxwillia** [comment]
The z=0.054 Consuelo boxes are now being used for the Triplets with M33 dynamics.  The distances are corrected for the different scale factor: D(t) = a(t)*D0, where D0 is the distance at redshift 0.  

As for the z=0.054 box having a different value of the hubble parameter, it seems as if Gadget does their evolution without any dependence on the explicit value of h. From their users manual under the HUBBLEPARAM section:

Note however that the value of HubbleParam is not needed (in fact, it does not enter the computation at
all) in purely collisionless simulations. This is because of the definition of GADGET-2’s system of units, which eliminates an explicit appearance of the value of the Hubble constant in the dynamical equations.

Can @yymao  confirm that this means h=0.7 is used for every redshift?

**Comment by yymao** [comment]
Yes. h is defined as a constant = H_0 / (100 km/s/Mpc). 

At higher redshifts, you may need to also correct the velocity. (There might be a factor of sqrt(a), but I need to check...)

**Comment by yymao** [comment]
Ah, actually I believe in the halo catalogs the velocities are already physical (not comoving).

**Comment by marxwillia** [comment]
Yes the velocities are already physical.  However the positions are comoving, so as long as they are multiplied by the scale factor, then the distance, radial velocity, and tangential velocity should all come out correctly.  And just to be clear, in the z=0.054 box, the comoving distance is given by D = sqrt(x^2 +y^2 +z^2), where the x,y,z values are taken from the z=0.054 hlist.  To transform to physical units, the scale factor is multiplied by each position ie x --> ax, y --> ay, z --> az.

**Comment by yymao** [comment]
yes. that's right.

**Comment by drphilmarshall** [comment]
Excellent! Does this mean we have twice as many triplets now? Do the demo
and thesis plots reflect this? Great if you can re-post the link to the
appropriate thing to look at, please.
