### ISSUE TITLE
Add Quad Functionality

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#71]
We will not use Triplets for anything other than testing the GMM.  Quad functionality is pretty much already built into the isolation criteria, but it needs to be added into the coordinate transformation code.  

* [x] Find observed properties (RA, DEC, etc) in literature and add papers to litter
* [x] Update observations.py and sampling.py to include LMC
* [x] Transform LMC kinematics to MW centric frame.
* [x] Add LMC's D, vr, vt to likelihood calculation

**Comment by drphilmarshall** [comment]
Pretty sure @marxwillia nailed the quads some time ago!
